<?xml version="1.0" ?>
<robot name="hall_urdf" xmlns:xacro="http://www.ros.org/wiki/xacro">

<macro name="cylinder_inertia" params="m r h">
      <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                  iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
                  izz="${m*r*r/2}" /> 
      </macro>

<macro name="box_inertia" params="m x y z">
        <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
                  iyy="${m*(x*x+z*z)/12}" iyz = "0"
                  izz="${m*(x*x+z*z)/12}" /> 
</macro>

<macro name="sphere_inertia" params="m r">
        <inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
                  iyy="${2*m*r*r/5}" iyz = "0"
                  izz="${2*m*r*r/5}" /> 
</macro>

<!-- hall -->
<xacro:macro name = "hall_urdf" params = "hall_prefix hall_parent width=11 depth=8 height=3 *origin">

  <joint name="${hall_prefix}hall_joint" type="fixed">
    <xacro:insert_block name="origin" />
    <parent link="${hall_parent}"/>
    <child link="${hall_prefix}floor"/>
  </joint>


    <xacro:property name="dummy_thickness" value="0.01" />
    <xacro:property name="dummy_mass" value="100" />

  <material name="${hall_prefix}floor_color">
    <color rgba="${0/255} ${255/255} ${0/255} 1"/>
  </material>

  <material name="${hall_prefix}wall1_color">
    <color rgba="${255/255} ${255/255} ${0/255} 1"/>
  </material>

  <material name="${hall_prefix}wall2_color">
    <color rgba="${255/255} ${255/255} ${0/255} 1"/>
  </material>

    <link name="${hall_prefix}floor">
        <visual>
            <geometry>
             <box size="${depth} ${width} ${dummy_thickness}"/>
            <origin xyz="0 0 -${dummy_thickness}" rpy="0 0 0" />
            </geometry>
            <material name="${hall_prefix}floor_color"/>
        </visual>
      <collision>
            <geometry>
             <box size="${depth} ${width} ${dummy_thickness}"/>
            <origin xyz="0 0 -0.1" rpy="0 0 0" />
            </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <xacro:box_inertia m="${dummy_mass}" x="${depth}" y="${width}" z="${dummy_thickness}"/>
        <mass value="${dummy_mass}" />
      </inertial>
    </link>

    <link name="${hall_prefix}wall1">
        <visual>
            <geometry>
             <box size="${depth} ${height} ${dummy_thickness}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 -${dummy_thickness}"/>
            <material name="${hall_prefix}wall1_color"/>
        </visual>
      <collision>
            <geometry>
             <box size="${depth} ${height} ${dummy_thickness}"/>
            </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <xacro:box_inertia m="${dummy_mass}" x="${depth}" y="${height}" z="${dummy_thickness}"/>
        <mass value="${dummy_mass}" />
      </inertial>
    </link>

    <joint name="${hall_prefix}floor_to_wall1" type="fixed">
        <parent link="${hall_prefix}floor"/>
        <child link="${hall_prefix}wall1"/>
        <origin rpy="1.56 0 0" xyz="0 ${0.5 * width} ${0.5 * height}"/>
    </joint>

    <link name="${hall_prefix}wall2">
        <visual>
            <geometry>
             <box size="${height} ${width} ${dummy_thickness}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 -${dummy_thickness}"/>
            <material name="${hall_prefix}wall2_color"/>
        </visual>
      <collision>
            <geometry>
             <box size="${height} ${width} ${dummy_thickness}"/>
            </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <xacro:box_inertia m="${dummy_mass}" x="${height}" y="${width}" z="${dummy_thickness}"/>
        <mass value="${dummy_mass}" />
      </inertial>
    </link>

    <joint name="${hall_prefix}floor_to_wall2" type="fixed">
        <parent link="${hall_prefix}floor"/>
        <child link="${hall_prefix}wall2"/>
        <origin rpy="0 1.56 0" xyz="${0.5 * depth} 0 ${0.5 * height}"/>
    </joint>


    <link name="${hall_prefix}wall3">
        <visual>
            <geometry>
             <box size="${depth} 0.5 ${dummy_thickness}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 -${dummy_thickness}"/>
            <material name="${hall_prefix}wall1_color"/>
        </visual>
      <collision>
            <geometry>
             <box size="${depth} 0.5 ${dummy_thickness}"/>
            </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <xacro:box_inertia m="${dummy_mass}" x="${depth}" y="0.5" z="${dummy_thickness}"/>
        <mass value="${dummy_mass}" />
      </inertial>
    </link>

    <joint name="${hall_prefix}world_interface_to_wall3" type="fixed">
        <parent link="${hall_prefix}floor"/>
        <child link="${hall_prefix}wall3"/>
        <origin rpy="1.56 0 0" xyz="0 -${0.5 * width} ${0.5 * 0.5}"/>
    </joint>


    <link name="${hall_prefix}wall4">
        <visual>
            <geometry>
             <box size="0.5 ${width} ${dummy_thickness}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 -${dummy_thickness}"/>
            <material name="${hall_prefix}wall2_color"/>
        </visual>
      <collision>
            <geometry>
             <box size="0.5 ${width} ${dummy_thickness}"/>
            </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <xacro:box_inertia m="${dummy_mass}" x="0.5" y="${width}" z="${dummy_thickness}"/>
        <mass value="${dummy_mass}" />

      </inertial>
    </link>

    <joint name="${hall_prefix}world_interface_to_wall4" type="fixed">
        <parent link="${hall_prefix}floor"/>
        <child link="${hall_prefix}wall4"/>
        <origin rpy="0 1.56 0" xyz="-${0.5 * depth} 0 ${0.5 * 0.5}"/>
    </joint>



  <gazebo reference="${hall_prefix}floor">
    <material>Gazebo/Green</material>
  </gazebo>

  <gazebo reference="${hall_prefix}wall1">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <gazebo reference="${hall_prefix}wall2">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <gazebo reference="${hall_prefix}wall3">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <gazebo reference="${hall_prefix}wall4">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <!-- Gazebo -->
  <xacro:include filename="$(find casus_support)/urdf/hall/hall.gazebo.xacro"/>

</xacro:macro>
</robot>



